name: myenv
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pytorch=2.5
  - rdkit
  - numpy
  - pandas
  - Flask
  - chemprop==2.0.0
  - werkzeug
  - urllib3
  - requests
  - scikit-learn
  - pyyaml