name: myenv
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3
  - pip
  - pip:
    - -r requirements.txt 
  - rdkit
  - joblib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - boto3
  - gunicorn
  - Flask
  - chemprop
  - mkl
  - pytorch=*=*cuda11.3*
  - torchvision=*=*_cu*
  - torchaudio=*=*_cu*
  - cudatoolkit<=11.4
  - cuDNN=8.3
