name: Help

on:
  workflow_dispatch: { }
  push:
    paths:
      - 'help/**'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Markdown
        id: check
        uses: docker://ghcr.io/igorshubovych/markdownlint-cli:latest
        with:
          args: --output help/lint-check-report.md --config .github/linters/.markdownlint.yaml "help/**/*.md"
      - name: Set summary
        if: always()
        run: |
          echo "## Summary" >  "${GITHUB_STEP_SUMMARY}"
          if [ -s help/lint-check-report.md ]; then
            echo ":no_entry_sign: Some errors occured" >> "${GITHUB_STEP_SUMMARY}"
            echo "## Errors per input" >> "${GITHUB_STEP_SUMMARY}"
            cat help/lint-check-report.md >> "${GITHUB_STEP_SUMMARY}"
          else
            echo ":white_check_mark: Successful" >> "${GITHUB_STEP_SUMMARY}"
          fi

  link_check:
    name: Check links
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Markdown links
        uses: lycheeverse/lychee-action@76ab977fedbeaeb32029313724a2e56a8a393548
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_TOKEN }}
        with:
          args: "--exclude-all-private --require-https --cache -a 429 --verbose --no-progress 'help/**/*.md'"
          fail: true
          jobSummary: true
          format: markdown
          output: help/link-check-report.md

  convert:
    name: Convert to HTML
    needs: [ lint, link_check ]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Lua Filters for Pandoc
        run: |
          cat <<EOT > links-to-html.lua
          function Link(el)
            el.target = string.gsub(el.target, "%.md", ".html")
            return el
          end
          EOT
          cat <<EOT > table-id.lua
          function Table(el)
            el.attr.identifier = "help-table"
            return el
          end
          EOT
      - name: Create entrypoint for Pandoc
        working-directory: ./help
        run: |
          echo '#!/bin/sh' > entrypoint.sh
          files="$(find . -type f -name '*.md' -not -path "*/_*" -not -name '*-test.md' -printf '%P ')"
          for f in $files; do
            if [[ "$(dirname ${f})" == "." ]]; then
              dir=''
            else
              dir=$(dirname "${f}")
            fi
            mkdir -p "output/help/${dir}";
            echo "cd /github/workspace/help/output/help/${dir}" >> entrypoint.sh;
            echo "pandoc -f gfm -t html --resource-path=.:/github/workspace/help/${dir} --lua-filter=/github/workspace/links-to-html.lua --lua-filter=/github/workspace/table-id.lua --output=/github/workspace/help/output/help/${f/.md/.html} \"/github/workspace/help/${f}\"" >> entrypoint.sh;
          done;
          media="$(find . -type f \( -name '*.gif' -o -name '*.jpeg' -o -name '*.jpg' -o -name '*.png' -o -name '*.bmp' \) -printf '%P ')"
          for m in $media; do
            if [[ "$(dirname ${m})" == "." ]]; then
              dir=''
            else
              dir=$(dirname "${m}")
            fi
            mkdir -p "output/help/${dir}";
            echo "cp /github/workspace/help/${m} /github/workspace/help/output/help/${m}" >> entrypoint.sh;
          done;
      - name: Convert Mardown to HTML
        uses: docker://pandoc/core:latest
        with:
          entrypoint: /bin/sh
          args: /github/workspace/help/entrypoint.sh
      - name: Apply internal styles to HTML which is not supported by pandoc yet
        working-directory: ./help
        run: |
          for f in output/help/**/*.html; do
            sed -i -e '0,/<p>/s//<p class="d4-help-info">/' "$f";
          done;
      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 1.24.3
      - uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/dart-sdk-1.24.3
          key: dart-1.24.3-install-cache
      - name: Install Dart dependencies
        run: pub get
        working-directory: ./help/_internal
      - name: Run Dart script to create menu
        run: dart generate_menu.dart -s ../output/help/ -d ../output/help/
        working-directory: ./help/_internal
      - name: Move output HTML files
        id: move
        run: mv help/output/ output/
      - name: Install anchor-check
        run: npm install -g @untitaker/hyperlink
      - name: Check anchors
        id: anchors
        run: |
          hyperlink --check-anchors output/ --sources help/ >  help/anchor-check-report.md 2>&1
      - name: Set summary
        if: always() && (steps.anchors.outcome == 'failure' || steps.anchors.outcome == 'success')
        run: |
          echo "## Summary" >  "${GITHUB_STEP_SUMMARY}"
          if [[ "${{ steps.anchors.outcome }}" == "failure" ]]; then
            echo ":no_entry_sign: Some errors occured" >> "${GITHUB_STEP_SUMMARY}"
            cat help/anchor-check-report.md >> "${GITHUB_STEP_SUMMARY}"
            sed -i '/Found some broken links, reading source files/a ## Errors per input' ${GITHUB_STEP_SUMMARY}
            sed -i -r 's,^(help/.*\.md)$,### \1,g' ${GITHUB_STEP_SUMMARY}
            sed -i 's,error:,**Error:**,g' ${GITHUB_STEP_SUMMARY}
            sed -i -r 's,(at line [0-9]+),**\1**,g' ${GITHUB_STEP_SUMMARY}
            sed -i -r 's,^(output/help.*\.html)$,### \1,g' ${GITHUB_STEP_SUMMARY}
            sed -i -r '/^Found [0-9]+ bad links/i ## Errors summary' ${GITHUB_STEP_SUMMARY}
          else
            echo ":white_check_mark: Successful" >> "${GITHUB_STEP_SUMMARY}"
          fi

      - name: 'Upload Artifact'
        if: always() && steps.move.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: help_html_pages
          path: output
          retention-days: 7

  deploy:
    name: Deploy
    needs: convert
    concurrency:
      group: help-deploy-${{ github.ref }}
      cancel-in-progress: true
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    environment: Help
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: help_html_pages
      - name: Deploy to server
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 400 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          rsync \
            --recursive \
            --links \
            --times \
            --omit-dir-times \
            --group --owner \
            --chown=grok:grok \
            --perms --executability --acls --xattrs \
            --devices --specials \
            --checksum \
            --delete-after \
            --compress \
            --update \
            --verbose \
            --progress \
            --itemize-changes \
            --stats \
            --human-readable \
            "help/" "$REMOTE_USER@$REMOTE_HOST:$TARGET"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HELP_SSH_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.HELP_KNOWN_HOST }}
          REMOTE_HOST: ${{ secrets.HELP_HOST }}
          REMOTE_USER: ${{ secrets.HELP_USER }}
          TARGET: ${{ secrets.WIKI_DOCS_TARGET }}
